# Generated by Django 2.2.12 on 2020-06-23 06:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borehole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bholeDateOfDrilling', models.DateField(null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GW_GeologyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phenomenonTime', models.DateTimeField(blank=True, null=True)),
                ('resultTime', models.DateTimeField(blank=True, null=True)),
                ('parameter', models.TextField(blank=True, null=True)),
                ('gw_level', models.FloatField(blank=True, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.TextField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WellStatusTypeTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GW_Well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gwwellname', models.TextField()),
                ('gwwelllocation', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('gwwellcontributionzone', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('gwwelltotallength', models.FloatField(blank=True, null=True)),
                ('gwwellconstruction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groundwater.Borehole')),
                ('gwwellgeology', models.ManyToManyField(blank=True, null=True, to='groundwater.GW_GeologyLog')),
                ('gwwellstaticwaterdepth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groundwater.Quantity')),
                ('gwwellstatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groundwater.WellStatusTypeTerm')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='gw_geologylog',
            name='endDepth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endDepth', to='groundwater.Quantity'),
        ),
        migrations.AddField(
            model_name='gw_geologylog',
            name='startDepth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startDepth', to='groundwater.Quantity'),
        ),
        migrations.AddField(
            model_name='borehole',
            name='bholeNominalDiameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groundwater.Quantity'),
        ),
    ]
